name: Deploy Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - name: publish
        run: |
          echo "repository variable : ${{ vars.VSCE_PUBLISHER_TOKEN }}"
          run: npx @vscode/vsce publish --token ${{ vars.VSCE_PUBLISHER_TOKEN }}