name: Deploy Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - name: publish
        env:
          PUBLISHER_TOKEN: ${{ vars.VSCE_PUBLISHER_TOKEN }}
        run: |
          echo "repository variable : $PUBLISHER_TOKEN"
          run: npx @vscode/vsce publish --token $PUBLISHER_TOKEN