name: Deploy Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      PUBLISHER_TOKEN: ${{ secrets.VSCE_PUBLISHER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - name: publish
        run: |
          run: echo "My APP_ID value in the production job is $PUBLISHER_TOKEN"
          run: npx @vscode/vsce publish --token $PUBLISHER_TOKEN