name: Deploy Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - name: publish
        run: npx @vscode/vsce publish --token ${{ secrets.VSCE_PUBLISHER_TOKEN }}