name: Deploy Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      PUBLISHER_TOKEN: ${{ secrets.VSCE_PUBLISHER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - name: publish
        run: |
          npx @vscode/vsce publish --pat $PUBLISHER_TOKEN